### ISSUE TITLE
[Bug]: Business Table Crashing in Grafana Cloud, but functioning in On Premises Open Source

### ISSUE THREAD

**Issue by quanita-s** [VolkovLabs/business-table#324]
### Summary

Business Table Error (crash) when adding or editing a table in the Layout Section of the panel.  In some instances, you can add a new table, and it crashes when you try to edit. In some cases it crashes when you try to add a table in layout section. 

**This only happens in Grafana Cloud**

Happy to provide additional logging or info with instructions on how to get them or ask sys admins for additional information.

### Steps to Reproduce

1. Add new panel to dashboard
2. Change Visualisation Type to Business Table
3. Add table in Layout Panel (sometime error occurs here)
4. Expand table to select columns in Layout Panel (sometimes error occurs here)

### Expected Behavior

Table is added to Layout panel
Table reads queries for dataset that can be added to the table

### Actual Behavior

An unexpected error happened
details (details are pasted in Additional Context section below)

### Environment Details

- **Plugin Version**: 2.6.0 and 2.5.0
- **Grafana Version**: Cloud (steady)
- **Datasource(s)**: [postgres - but this happens with any default and with no data source as well]
- **Operating System**: (Client - Windows 11) - Server unsure
- **Browser**:  Microsoft Edge Version 137.0.3296.52 (Official build) (64-bit)
- **Deployment Type**:  

### Severity

Low (Minor issue, workaround available)

### Did this work in a previous version?

- [x] Yes, it worked before
- [ ] No, it never worked
- [ ] Not sure

### Details of Previous Working Version (if applicable)

Plugin Version 2.5.0
Works fine in Grafana v11.3.0 (d9455ff7db) (On Premises deployment)

### Error for 2.5.0
An unexpected error happened
Details
TypeError: (0 , a.getFieldTypeIcon) is not a function

    at Hb (https://plugins-cdn.grafana.net/volkovlabs-table-panel/2.5.0/public/plugins/volkovlabs-table-panel/module.js:366:7438)
    at yE (https://plugins-cdn.grafana.net/volkovlabs-table-panel/2.5.0/public/plugins/volkovlabs-table-panel/module.js:366:73956)
    at IS (https://plugins-cdn.grafana.net/volkovlabs-table-panel/2.5.0/public/plugins/volkovlabs-table-panel/module.js:399:5758)
    at div
    at div
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:175462
    at g (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:223:6441)
    at div
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:223:1898
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:125:1475
    at div
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:1:159142
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:1:171226
    at push.89451.Component (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:125:6047)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:15:76504)
    at div
    at div
    at lt (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:122:92792)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:15:76504)
    at div
    at w (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:109:90954)
    at Ro (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:125:94069)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:15:76504)
    at vm (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:17:219733)
    at j (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/8528.3ce6c049e8a3885a05f6.js:1:5042)
    at Do (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/8528.3ce6c049e8a3885a05f6.js:3:94876)
    at Suspense
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:158588)
    at N (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:6427)
    at H (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:7108)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:4569)
    at Gn (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:12208)
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:1:161616
    at main
    at div
    at div
    at div
    at aa (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:98661)
    at Er (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:104809)
    at rr (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:105978)
    at l (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:232:209758)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:4569)
    at Gn (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:12208)
    at on (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:11541)
    at pt (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:247:18355)
    at E (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:5:185505)
    at ze (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:42599)
    at jr (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:106246)
    at div
    at d (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:109:20478)
    at c (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:242:77246)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:20853)
    at C (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:152:9065)
    at E (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:386:42739)
    at C (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/9597.bc94c0ca3c2b48c0d187.js:174:36400)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:24:12419)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:158588)
    at i (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:159134)
    at Ke (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/9597.bc94c0ca3c2b48c0d187.js:178:516)
    at fo (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:106721)

**Error for 2.6.0**

TypeError: (0 , a.getFieldTypeIcon) is not a function

    at Zb (https://plugins-cdn.grafana.net/volkovlabs-table-panel/2.6.0/public/plugins/volkovlabs-table-panel/module.js:366:7438)
    at TE (https://plugins-cdn.grafana.net/volkovlabs-table-panel/2.6.0/public/plugins/volkovlabs-table-panel/module.js:366:73956)
    at zS (https://plugins-cdn.grafana.net/volkovlabs-table-panel/2.6.0/public/plugins/volkovlabs-table-panel/module.js:399:5758)
    at div
    at div
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:175462
    at g (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:223:6441)
    at div
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:223:1898
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:125:1475
    at div
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:1:159142
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:1:171226
    at push.89451.Component (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:125:6047)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:15:76504)
    at div
    at div
    at lt (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:122:92792)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:15:76504)
    at div
    at w (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:109:90954)
    at Ro (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:125:94069)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:15:76504)
    at vm (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:17:219733)
    at j (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/8528.3ce6c049e8a3885a05f6.js:1:5042)
    at Do (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/8528.3ce6c049e8a3885a05f6.js:3:94876)
    at Suspense
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:158588)
    at N (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:6427)
    at H (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:7108)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:4569)
    at Gn (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:12208)
    at div
    at https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:1:161616
    at main
    at div
    at div
    at div
    at aa (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:98661)
    at Er (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:104809)
    at rr (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:105978)
    at l (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:232:209758)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:4569)
    at Gn (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:12208)
    at on (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:11541)
    at pt (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:247:18355)
    at E (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:5:185505)
    at ze (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:256:42599)
    at jr (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:106246)
    at div
    at d (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:109:20478)
    at c (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:242:77246)
    at le (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:20853)
    at C (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:152:9065)
    at E (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/2961.6b7b46a8371d3d817b32.js:386:42739)
    at C (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/9597.bc94c0ca3c2b48c0d187.js:174:36400)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/6123.e2d085f36d5b4ac1ca1d.js:24:12419)
    at m (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:158588)
    at i (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:12:159134)
    at Ke (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/9597.bc94c0ca3c2b48c0d187.js:178:516)
    at fo (https://grafana-assets.grafana.net/grafana/12.1.0-88993/public/build/5907.081a9635a06afc78d1c6.js:108:106721)

### Confirmation

- [x] I have searched for existing issues and confirmed this is not a duplicate.
- [x] I have provided all required information to the best of my ability.

**Comment by mikhail-vl** [comment]
@quanita-s Thank you for reporting the issue. It's a know issue in the latest Grafana Cloud updates waiting for be merged: https://github.com/grafana/grafana/pull/106168.
